### ISSUE TITLE
"Server/ Client" Customer can add a product to sell

### ISSUE THREAD

**Issue by JoeShep** [nss-cohort-40/bangazon-ecommerce-api-silly-walkers-ecommerce-api#1]
**Given** the user is not authenticated
**When** any view renders
**Then** the *Sell a Product* affordance will not be visible

**Given** the user is authenticated
**When** the user clicks on the *Sell a product* button in the menu bar
**Then** the user will be presented with a product form

**Given** the user has filled in all fields of the product form with valid information
**When** the user clicks the *Sell* button
**Then** the user will be redirected to the product detail view for that product

**Given** the user has filled in all fields of the product form with any invalid information
**When** the user clicks the *Sell* button
**Then** the user will be immediately notified with error information for each invalid value

**Comment by sarahholder** [comment]
Server side**

**Comment by tstrotherIV** [comment]
### What (Client-Side)
-->Sell Product menu option(ONLY VISIBLE WHEN LOGGED IN!!!!!!)

• Form to create and add a new Product  pops up
• input type checks (client-side or server-side??)

? If input types all pass : 
--> Newly created product details page

**Comment by tstrotherIV** [comment]
### How (Client-Side)

• Creation form with a submit
•Upond submit input type checks occur (client-side or server-side??)

? If input types all pass : 
--> Newly created product details page

**Comment by tstrotherIV** [comment]
### Dependency (Client-Side)

• User/Customer being logged in
• User Id

**Comment by tstrotherIV** [comment]
### What (Server Side)

• When the client-side sends the POST request, the Products POST method will be executed
• That product will be added to the API database
• The new product info will be sent back to the user for the product details page upon completion.

**Comment by tstrotherIV** [comment]
### How (Server-Side)
•When the API received the DELETE fetch call from the Client side, the DELETE method on the Product view will be executed.

**Comment by tstrotherIV** [comment]
### Dependency

•Customer Id
•Product Type Table (Dropdown?)
•Product Type needs to exist
