### ISSUE TITLE
CLIENT && SERVER -- User can add a payment type

### ISSUE THREAD

**Issue by JoeShep** [nss-cohort-40/bangazon-ecommerce-api-silly-walkers-ecommerce-api#7]
**Given** the user is authenticated
**When** the user clicks on a profile affordance in the navigation bar
**And** the user clicks on the *Add Payment Option* hyperlink in their profile
**Then** the user can fill out the payment option form
**And** click *Submit* to save payment option

**Comment by kirksudduth** [comment]
### What Doing? (CLIENT)
- user clicks on **Profile** in NavBar
- user clicks on **Add Payment Type** hyperlink that is contained in ***Profile*** view
- user is directed to **Add Payment Type Form** view
- user can save *Payment Type* onClick **Submit** button that will return user to **Profile** view

### What Doing? (SERVER)
- when user submits form -- a **POST** method is run to the *Payment Type* table in the db
